name: histudy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  flutterfire_ui: ^0.3.1
  google_sign_in: ^5.3.0
  flutter_svg: ^1.0.3
  dropdown_button2: ^1.4.0


dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/